from . import car_color
from . import car_lot_image
from . import car_expense
from . import car_location_history
from . import car_audit_log
from . import car_test_drive
from . import product_template
from . import stock_lot
from . import crm_lead
from . import sale_order
from . import sale_order_line
from . import purchase_order
from . import stock_picking
from . import stock_landed_cost
from . import account_move
from . import res_config_settings
